openapi: "3.0.0"

info:
  title: API specs for Scheduling
  description:
    Scheduling API paths and entity is defined in this file.
  version: "1.0.2"

servers:
  - url: ""

tags:
  - name: Scheduling
    description: APIs for managing Scheduling Delivery