openapi: "3.0.0"

info:
  title: API specs for Summons
  description:
    Summons API paths and entity is defined in this file.
  version: "1.0.2"

servers:
  - url: ""

tags:
  - name: Summons
    description: APIs for managing Summons Delivery